export const employees = [
    {
      id_data_pegawai: "1",
      nama: "Luthfi Naufal Wibisono",
      umur: "22",
      tanggal_lahir: "2002-08-07",
      gender: "Laki-laki",
      alamat: "Jalan Raya Puncak, Desa Cisarua, Bogor, Jawa Barat",
      email_kantor: "luthfi.22088@mhs.unesa.ac.id",
      password: "luthfi",
      notelp: "083833443621",
      status_pernikahan: "Belum menikah",
      nik: "1234588040215022",
      jabatan: "Systems Analyst",
      gaji: "9.250.000",
      skills: ["Data Analysis", "System Design", "Problem Solving"]
    },
    {
      id_data_pegawai: "2",
      nama: "Muhammad Miftakul Salam",
      umur: "21",
      tanggal_lahir: "2003-12-27",
      gender: "Laki-laki",
      alamat: "Jalan Sudirman No. 123, Kota Semarang, Jawa Tengah",
      email_kantor: "muhammadmiftakul.22101@mhs.unesa.ac.id",
      password: "mifta",
      notelp: "089676360546",
      status_pernikahan: "Belum menikah",
      nik: "1234510140215022",
      jabatan: "Front-end Developer",
      gaji: "9.500.000",
      skills: ["HTML", "CSS", "JavaScript", "React.js"]
    },
    {
      id_data_pegawai: "3",
      nama: "Raihan",
      umur: "24",
      tanggal_lahir: "2000-3-12",
      gender: "Laki-laki",
      alamat: "Perumahan Graha Asri Blok A2 No. 5, Kelurahan Karang Anyar, Surakarta, Jawa Tengah",
      email_kantor: "raihan.22086@mhs.unesa.ac.id",
      password: "raihan",
      notelp: "085606304312",
      status_pernikahan: "Belum menikah",
      nik: "1234568040215022",
      jabatan: "Project Manager",
      gaji: "14.000.000",
      skills: ["Project Management", "Leadership", "Team Collaboration"]
    },
    {
      id_data_pegawai: "4",
      nama: "Raynaldi Lalensang",
      umur: "22",
      tanggal_lahir: "2002-5-28",
      gender: "Laki-laki",
      alamat: "Jalan Gatot Subroto No. 56, Kota Malang, Jawa Timur",
      email_kantor: "raynaldi.22087@mhs.unesa.ac.id",
      password: "raynaldi",
      notelp: "082139931885",
      status_pernikahan: "Belum menikah",
      nik: "1234578040215022",
      jabatan: "Database Administrator",
      gaji: "11.000.000",
      skills: ["Database Management", "SQL", "Data Security"]
    },
    {
      id_data_pegawai: "5",
      nama: "Vincent Louis Fernando",
      umur: "21",
      tanggal_lahir: "2003-9-19",
      gender: "Laki-laki",
      alamat: "Komplek Permata Hijau Blok C1 No. 10, Kelurahan Gading, Jakarta Barat",
      email_kantor: "vincent.22097@mhs.unesa.ac.id",
      password: "vincent",
      notelp: "085232025136",
      status_pernikahan: "Belum menikah",
      nik: "1234579040215022",
      jabatan: "Back-end Developer",
      gaji: "9.400.000",
      skills: ["Java", "Spring Boot", "RESTful APIs", "Database Integration"]
    }
  ];
  